DFHack/stonesense

CMakeLists.txt

This modifies stonesense's CMakeLists to use the DFHACK_TINYXML variable set when building dfhack to either "dfhack-tinyxml" (the bundled copy of tinyxml) or "tinyxml", in which case we try to link against a copy of tinyxml present on the system.
See https://github.com/DFHack/dfhack/pull/950; I'm opening this pull request because I see that was merged. :)

Replace dfhack-tinyxml with DFHACK_TINYXML variable

---

common.h

Broken by RemoteFortressReader update: https://github.com/DFHack/dfhack/pull/1200

Fix Linux build (X11 defines Status to mean int)

---

common.h

this fixes `GLhandleARB` not being defined

include <GL/glext.h>

---

Tile.cpp
Tile.h
WorldSegment.h

0fb9abc5f8a7511269ab072317bbd366bc2fa9ca introduced some paths where Tile instances could be double-freed: specifically, `WorldSegment::Reset()` would call `Tile::InvalidateAndDestroy()` on individual tiles, followed by `delete[]` on the array containing them, and both of these call the Tile destructor.
Fixes an issue reported on Discord, and also fixes #73 (at least from my initial testing).
Marking as a draft because I would like to potentially revisit how Tile instances are stored. They contain at least one non-POD object (`Tile::building::sprites` is a vector, and in fact was what usually triggered the crash on my end), and the changes here _might_ result in some memory leaks if those are not freed properly.

Fix some Tile memory safety issues

---

Tile.cpp
Tile.h
WorldSegment.cpp
WorldSegment.h

Switch it back to using "tiles = new Tile[len]" and "delete[] tiles;", but this time just use ordinary method calls to attach/reset the tile instead of messing around with placement new and explicit destructor calls (which seemed safe on Windows but caused frequent crashes on Linux).
In essence, this is trying to accomplish what 0fb9abc5f8a7511269ab072317bbd366bc2fa9ca failed to do.

Rework allocation and initialization of Tiles

---

GUI.cpp
docs/Stonesense.rst

skips cleaning up, so this will leak memory. however, it will avoid crashing DF
Fixes: https://github.com/DFHack/stonesense/issues/101

work around crash after mega screenshot

---

SpriteMaps.cpp

Fix a possible crash when entering `GetTerrainSpriteMap` with an unsupported form. This would leave `tempform` uninitialized, later leading to an out of bound access. At the moment the fix is to just return the default sprite.
Note: I am completely unfamiliar with the codebase, and was not able to understand this situation "in context", so maybe there is a better way to fix that.
In my crash, I had:
```
material={type=426 index=27}
form=58
```
Which would translate to the material `PLANT:FLAX:THREAD`/`linen` and form would be `CLOTH`?
On my map they come from some pre-existing campsite and crashes as soon as one of the "tent" is in sight. This change is likely a fix for #75 given how similar the situation is.

Fix a crash with pre-existing campsite

---

GroundMaterialConfiguration.cpp

fake it for now until we can rewrite. a full fix would involve removing all signed comparisons for tiletypes and decoupling the tiletype fields from other int values that aren't tiletypes (e.g. `matchedness`)
ref: https://github.com/DFHack/df-structures/pull/774

df::tiletype is now unsigned, but our code assumes it is signed

---

Creatures.cpp
commonTypes.h

`DFHack::Units::MAX_COLORS` is being removed because it's not used (properly) anywhere, and is equivalent to `DFHack::COLOR_MAX` (AFAIK of its intent).
I've replaced the usage of it in Stonesense with the equivalent value of `15`, since it wasn't even being used as a color enum. The value is currently being used as however many elements of `unit.appearance.colors` we're willing to store in the `SS_Unit` struct. Note that these elements are used as indices to get `caste_raw` pattern data such as what color the unit's hair is at a given age. Stonesense only needs to know what color it is *right now*, so this is due for a rework.

Remove incorrect use of DFHack::Units::MAX_COLORS

---

WorldSegment.cpp
WorldSegment.h
docs/changelog.txt
main.cpp

The draw event for fog was pushing a pointer to the global fog bitmap, which would be regenerated after a resize, thus changing it address, thus leaving the draw event pointing to a freed object. The regeneration of the fog takes place _after_ the draw event is pushed to the draw event list.
This was resolved by creating a Fog draw event that does not hold a pointer to the fog bitmap; instead the draw event processor will grab the _current_ global fog bitmap at the time it processes a Fog draw event.
Also replaced `void *` in `draw_event` with a `std::variant` and did some other cleanup around resize processing
Fixes: https://github.com/DFHack/stonesense/issues/98
Fixes: https://github.com/DFHack/stonesense/issues/38
Fixes: https://github.com/DFHack/stonesense/issues/69

fix resize crash

---

main.cpp

this variable was moved to the global state holder, but i missed the original in `main.cpp` which resulted in the global value being shadowed in `main.cpp`. fixed.

use correct ssState instead of shadowed copy

---

GroundMaterialConfiguration.cpp
TreeGrowthConfiguration.cpp

This PR fixes a small logic error around XML parsing introduced while deduping in Part 3

Desmell, part 3a

---

docs/changelog.txt
main.cpp

Fixes stale window size information caused by the initial size being overwritten by a window manager. A resize event does not appear to be emitted, meaning it needs to be checked for directly.
Fixes #139

Fix stale window size information

---

Config.cpp
Config.h
GUI.cpp
GameConfiguration.h
MapLoading.cpp
UserInput.cpp
WorldSegment.cpp
configs/init.txt
docs/changelog.txt

Due to subpixel scaling, gaps could appear between tiles when zoomed in. This adds two new features which prevent these gaps from appearing.
`EXTRUDE_TILES` (on by default) expands every sprite by 1px in each direction, preventing gaps with minimal visual difference.
`PIXELPERFECT_ZOOM` (off by default) changes the scaling algorithm for zoom to be pixel perfect, losing some granularity in the process. This zoom algorithm does not work nicely with following DFs native zoom, so it is off by default.
Before:
After:

Add Gap-Removing Features

---

GUI.cpp
docs/changelog.txt

The initial offset for announcements is now offset based on font height.
`draw_border` will now also respect the font height instead of the calculated height for consistency between strings containing varying ascending/descending characters. `al_get_text_width` is now also used for determining box width, fixing an issue I encountered where text could render outside of the background.
Fixes #145

Properly offset announcements based on font size

---

docs/changelog.txt
resources/terrain/Track_Floors.xml
resources/terrain/Track_Ramps.xml
resources/terrain/index.txt

Cleaned up the outdated XMLs and tested the preexisting art.

Add back art for tracks in Stonesense

---

GUI.cpp
docs/changelog.txt

The performance timers all counted in allegro clock cycles, which did not line up with the unit being displayed. This converts the timing into milliseconds before displaying the timings.

Fix debug timers not displaying milliseconds

---

WorldSegment.cpp
docs/changelog.txt

The fog bitmap was only being used to store the fog color and nothing else. This replaces the fog bitmap with a call to `al_draw_filled_rectangle`.
Visuals should not change at all, and I had not noticed a notable performance difference when using an accelerated backend.

Remove uneccessary fog bitmap

---

configs/init.txt
docs/changelog.txt
main.cpp

This prevents sprites from going transparent when zooming out.
This is a temporary solution until our renderer supports setting a max mipmap LOD, in which case mipmapping may remain enabled. Allegro does not support this currently, and would require modification or an extension to implement properly.

Disable mipmapping with image_cache

---

Tile.cpp
Tile.h
docs/changelog.txt

The code was checking for hardcoded tiletype values instead of using the enum. As the values have shifted over time, some standard walls were being incorrectly treated as fortifications. This changes the function to refer to the enum values, ensuring they remain up to date.
Before:
After:

Fix some wall borders not being shown

---

SpriteObjects.cpp
docs/changelog.txt

Sprites were being culled for being off-screen because the check did not account for the y offsets that could occur. This updates the check to properly account for x and y offsets.
Fixes #171

Update sprite culling to account for offset

---

GameConfiguration.h
main.cpp

this is a less aggressive reset of the configuration state, intended as a short-term fix pending a more thorough refactoring of global state

don't shadow out overlay mode

---

docs/changelog.txt

Moves a changelog entry which was placed in an already-released portion during merge.
Fixes a typo in the configuration option `EXTRUDE_TILES`.

Minor changelog fixes

---

SpriteObjects.cpp
docs/changelog.txt

Fixes: https://github.com/DFHack/stonesense/issues/183

Tint the designations based on type, similar to DF

---

docs/changelog.txt

- "Dig-mode" bc its not just mining, its stairs and the like too.
- "More closely match" bc we show differences between a blueprint and an autodig turned blueprint.
- "Distinct colors" not distinctly

Clairify the designation tints better (and fix typo)

---

GUI.cpp
GameState.h
MapLoading.cpp
TrackingModes.cpp
UserInput.cpp
WorldSegment.cpp
commonTypes.h

This switches these two objects to a `std::optional`-wrapped `Crd3D` and switches logic for detecting invalid coordinates to point of initialization instead of point of use

optionalize `dfCursor` and `dfSelection`

---

ContentLoader.cpp

Add trap parsing to distinguish the traps and add more helpful text when we find unhandled things (because if we do they need to be added)

Update ContentLoader.cpp for traps
