- BuildingConfiguration.cpp
- BuildingConfiguration.h
- ConditionalSprite.cpp
- ConditionalSprite.h
- ConnectionState.cpp
- ConnectionState.h
- ContentBuildingReader.cpp
- ContentBuildingReader.h
- ContentLoader.cpp
- ContentLoader.h
- CreatureConfiguration.cpp
- CreatureConfiguration.h
- Creatures.cpp
- GUI.cpp
- GUI.h
- GameBuildings.cpp
- GroundMaterialConfiguration.cpp
- GroundMaterialConfiguration.h
- ItemConfiguration.cpp
- ItemConfiguration.h
- SpriteMaps.cpp
- TileCondition.cpp
- TileCondition.h
- VegetationConfiguration.cpp
- VegetationConfiguration.h
- WorldSegment.cpp
- WorldSegment.h
- commonTypes.h
- main.cpp
Use smart pointers throughout the stonesense codebase
> Smart pointers

- MaterialMatcher.h
> improve MaterialMatcher efficiency by avoiding needless wildcard matches

- ContentLoader.cpp
- Creatures.cpp
- GUI.cpp
- GameBuildings.cpp
- GroundMaterialConfiguration.cpp
- MapLoading.cpp
- SpriteObjects.cpp
- Tile.cpp
- UserInput.cpp
- VegetationConfiguration.cpp
- main.cpp
For https://github.com/DFHack/dfhack/pull/1958
> Fix warnings from -Wall

- Config.cpp
- GUI.cpp
- MapLoading.cpp
- Overlay.cpp
- TrackingModes.cpp
- TrackingModes.h
- UserInput.cpp
- commonTypes.h
- main.cpp
- resources/init.txt
Lot of fixmes here, but it runs, and doesn't immediately crash upon some quick testing.
> Got stonesense to compile and run.

- Config.cpp
- UserInput.cpp
- commonTypes.h
- resources/init.txt
Untested as don't yet have working 50.05 build environment again
> Invert mouse z

- MapLoading.cpp
The third half of https://github.com/DFHack/df-structures/pull/591
> use new tree root type

- ContentBuildingReader.cpp
- CreatureConfiguration.cpp
- Creatures.cpp
- GUI.cpp
- GameBuildings.cpp
- GroundMaterialConfiguration.cpp
- ItemConfiguration.cpp
- VegetationConfiguration.cpp
- WorldSegment.h
- main.cpp
2014 here we come!
(this is prerequisite to removing the dts workaround from dfhack itself)
> replace dts::make_unique with std::make_unique

- SpriteObjects.cpp
- Tile.cpp
ref: https://github.com/DFHack/df-structures/pull/774
> use new canonicalized structures and field names

- GUI.cpp
Announcements are now right aligned and limited to showing the 10 most recent ones. Will be a working user config in `init.txt` in future.
> Right align and limit the announcements

- .github/workflows/build.yml
Fixes: https://github.com/DFHack/stonesense/issues/117
> add docs CI check

- CMakeLists.txt
- ContentLoader.cpp
- GUI.cpp
- common.h
- main.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5176
> update both windows and linux to latest allegro

- CMakeLists.txt
> [stonesense] install allegro dlls on windows

- WorldSegment.cpp
fix locking error that got "fixed" by having the osd enabled
> [stonesense] make it safe to turn the osd off

- Creatures.cpp
- docs/changelog.txt
Fixes https://github.com/DFHack/stonesense/issues/13
> Fix Vampire name

- Config.cpp
- Config.h
- SpriteColors.cpp
- common.h
Adds 2 new ui colors (red and blue), publicizes clockToMs function, adds isViewTracking function
> Add a few things to aid development

- ContentBuildingReader.cpp
- ContentLoader.cpp
- ContentLoader.h
- Creatures.cpp
- DumpInfo.cpp
- GUI.cpp
- GameBuildings.cpp
- MaterialMatcher.h
- SpriteObjects.cpp
ref: https://github.com/DFHack/df-structures/pull/824
> Stonesense updates for the great reorg

- GUI.cpp
Simply a back end change. Should all work same as before.
> DRY-ed the cursor drawing to use a common function

- GUI.cpp
- SpriteColors.cpp
- SpriteColors.h
- main.cpp
Closes https://github.com/DFHack/stonesense/issues/217
> Streamline `uiColor()` to better match DF and increase clarity

- Tile.cpp
- docs/changelog.txt
Fixes https://github.com/DFHack/stonesense/issues/192
> Render items after buildings to layer them on top

- GUI.cpp
- docs/changelog.txt
Closes: https://github.com/DFHack/stonesense/issues/215
> Add a follow offset when spectating units

- GUI.cpp
> remove the view offset when not following a dorf

- ContentLoader.cpp
> Update ContentLoader.cpp for Civzones
